airflowHome: "/airflow"

executor: "KubernetesExecutor"
fernetKey: "DT7cPnm0nVpQExjr2ixA8qsf5eqRWNXkox3yuMVxCbo="

env:
  - name: AIRFLOW_HOME
    value: /airflow
  - name: AIRFLOW__CORE__TEST_CONNECTION
    value: Enabled

postgresql:
  enabled: false

statsd:
  enabled: false

data:
  metadataConnection:
    user: airflow
    pass: password
    protocol: postgresql
    host: host.docker.internal
    port: 30001
    db: airflow

# Stop database migration
migrateDatabaseJob:
  enabled: false

images:
  airflow:
    repository: docker.io/ducthuyng/test-airflow-rs-image
    tag: 0.2.2

# Logging
logs:
  persistence:
    enabled: true
    size: 1Gi
    existingClaim: sandboxunited-pvc

webserver:
  defaultUser:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 512Mi

  startupProbe:
    periodSeconds: 120
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 120

  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 80
        targetPort: 8080
        nodePort: 31000

scheduler:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

  startupProbe:
    periodSeconds: 120
  livenessProbe:
    initialDelaySeconds: 120

workers:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 512Mi

triggerer:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

cleanup:
  enabled: true
